"""adiciona_grupo_economico_cliente

Revision ID: 2bc7e3333923
Revises: cf83d3e00ab1
Create Date: 2026-09-07 19:13:23.545284

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2bc7e3333923'
down_revision: Union[str, Sequence[str], None] = 'cf83d3e00ab1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
