"""aumenta_tamanho_cnpj_cpf

Revision ID: fcd9d0c43f09
Revises: 
Create Date: 2026-09-04 20:20:21.199690

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'fcd9d0c43f09'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('clientes', 'cnpj_cpf',
               existing_type=sa.VARCHAR(length=18),
               type_=sa.String(length=64),
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('clientes', 'cnpj_cpf',
               existing_type=sa.String(length=64),
               type_=sa.VARCHAR(length=18),
               existing_nullable=True)
    # ### end Alembic commands ###
